# Swap out with http_archive in your own project
local_repository(
    name = "bazel_compile_commands",
    path = "../",
)

load("@bazel_compile_commands//:deps.bzl", "bazel_compile_commands_dependencies")

bazel_compile_commands_dependencies()

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python_3_11",
    python_version = "3.11",
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()
